on:
  workflow_dispatch:
env:
  ARCHIVE_URL: ${{ secrets.ARCHIVE_URL }}
jobs:
  unfollowers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        run: make build
      - name: Add build directory to path
        run: echo "${GITHUB_WORKSPACE}/build" >> $GITHUB_PATH
      - name: Download Instagram information locally
        run: instagram information download $ARCHIVE_URL
      - name: Find out which Instagram users are not following back
        run: instagram followdata unfollowers
      - name: Cleanup local Instagram information
        run: instagram information cleanup
