name: insights
on:
  workflow_dispatch:
env:
  ARCHIVE_URL: ${{ secrets.ARCHIVE_URL }}
jobs:
  unfollowers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: true
      - name: Download Instagram information locally
        run: go run main.go information download $ARCHIVE_URL
      - name: Find out which Instagram users are not following back
        run: go run main.go followdata unfollowers
      - name: Cleanup local Instagram information
        run: go run main.go information cleanup
